import type { Term, TermKind } from "./types";

function t(
  id: string,
  title: string,
  kind: TermKind,
  summary: string,
  body: string,
  extra?: Pick<Term, "live" | "code">,
): Term {
  return { id, title, kind, summary, body, ...extra };
}

export const terms: Record<string, Term> = {
  telemetry: t(
    "telemetry",
    "TelemetryCenter",
    "center",
    "Producer and owner of the append-only event_log — the system of record.",
    "[[duck-simulator|DuckSimulator]] emits [[squeaked|Squeaked]]. [[transactional-publisher|TransactionalPublisher]] writes duck state and the [[outbox]] in one transaction; [[outbox-dispatcher|OutboxDispatcher]] appends to [[event-log|event_log]]. Other Centers never write this database. [[no-shared-db|No shared DB]]. [[no-center-calls|No Center-to-Center calls]].",
    { live: "center" },
  ),
  alarm: t(
    "alarm",
    "AlarmCenter",
    "center",
    "Rate window on Squeaked. Raises and resolves alarms via its own outbox.",
    "A consumer: [[http-log-tail-feeder|HttpLogTailFeeder]] → [[hostile-transport|hostile]] wrappers → [[bus|IEventBus]] → [[upcast]] → [[shard-worker-pool|shards]] → [[per-key-sequencer|PerKeySequencer]] → [[retry-pipeline|RetryPipeline]] → [[inbox]] + [[alarm-store|AlarmStore]]. Own SQLite. Emits [[alarm-raised|AlarmRaised]] / [[alarm-resolved|AlarmResolved]] through [[remote-outbox-dispatcher|RemoteOutboxDispatcher]].",
    { live: "center" },
  ),
  dashboard: t(
    "dashboard",
    "DashboardCenter",
    "center",
    "Disposable CQRS projector. Hour buckets can be deleted and rebuilt from the log.",
    "Projects [[squeaked|Squeaked]] into [[squeaks-by-duck-hour]]. [[inbox]] dedupes; there is no [[per-key-sequencer|PerKeySequencer]] because hour counts [[commutative|commute]] under shuffle. [[rebuild]] truncates and replays from offset 0. This SPA is a browser; it is not a Center-to-Center call.",
    { live: "center" },
  ),
  billing: t(
    "billing",
    "BillingCenter",
    "center",
    "Saga on alarm facts. Reserve a fee, then release or timeout-compensate.",
    "Subscribes to [[alarm-raised|AlarmRaised]] and [[alarm-resolved|AlarmResolved]]. Never calls AlarmCenter. [[billing-sagas]] keyed by alarm id. Fast path: resolve → [[fee-released|FeeReleased]]. Slow path: [[saga-timeout-worker|timeout worker]] expires a still-Reserved saga. Own SQLite.",
    { live: "center" },
  ),
  bus: t(
    "bus",
    "IEventBus",
    "center",
    "A port, not a Center. Adapters: RabbitMQ in Aspire, in-memory in tests.",
    "[[event-bus-factory|EventBusFactory.Create()]] picks [[rabbitmq-event-bus|RabbitMqEventBus]] or [[in-memory-event-bus|InMemoryEventBus]]. Inbox and sequencer are not inside the bus. Duplicate [[event-id|EventId]] is [[at-least-once|at-least-once]] delivery. [[http-log-client|HttpLogClient]] tails and appends the [[event-log|log]].",
    { live: "center" },
  ),

  "no-center-calls": t(
    "no-center-calls",
    "No Center-to-Center calls",
    "rule",
    "Centers integrate only through events. Never HTTP to another Center’s business API.",
    "Alarm does not call Billing. Billing does not call Alarm. The Dashboard UI polls as a browser; that is not a Center. The only integration seam is [[bus|IEventBus]] plus each Center appending facts to [[event-log|event_log]].",
  ),
  "no-shared-db": t(
    "no-shared-db",
    "No shared database",
    "rule",
    "Each Center owns its SQLite file and schema. There is no ducknet.db in the middle.",
    "[[telemetry|Telemetry]] owns [[event-log|event_log]]. Alarm owns [[alarms]] and [[squeak-window]]. Dashboard owns [[squeaks-by-duck-hour]]. Billing owns [[billing-sagas]]. [[inbox]], offsets, and [[dlq|DLQ]] are per Center.",
  ),
  "events-are-facts": t(
    "events-are-facts",
    "Events are past facts",
    "rule",
    "Names are past tense. Squeaked, not SqueakTheDuck. A fact, not a command.",
    "[[squeaked|Squeaked]], [[alarm-raised|AlarmRaised]], [[alarm-resolved|AlarmResolved]], [[fee-reserved|FeeReserved]], [[fee-released|FeeReleased]]. Handlers react. They do not tell another Center what to do.",
  ),
  "hostile-transport": t(
    "hostile-transport",
    "Hostile transport",
    "rule",
    "At-least-once, unordered across keys. Duplicator and Shuffler run after the log read, never before append.",
    "[[duplicator-shuffler|Duplicator + Shuffler]] wrap the consumer after [[http-log-tail-feeder|HttpLogTailFeeder]]. The [[event-log|log]] stays ordered. [[inbox]] survives duplicates. [[per-key-sequencer|PerKeySequencer]] restores per-duck order where the handler needs it.",
  ),
  "at-least-once": t(
    "at-least-once",
    "At-least-once delivery",
    "rule",
    "The same EventId may arrive more than once. Inbox is the dedupe, not the bus.",
    "Crash mid-handle, ack-after-enqueue, or [[duplicator-shuffler|Duplicator]] can clone a row. [[inbox]] records the [[event-id|EventId]] in the same transaction as the side effect. A second delivery is a no-op.",
  ),

  "event-envelope": t(
    "event-envelope",
    "EventEnvelope",
    "event",
    "The wire type. Payload is JSON; identity and tracing ride on the envelope.",
    "Fields that matter: [[event-id|EventId]], [[partition-key|PartitionKey]], [[sequence-number|SequenceNumber]], [[version|Version]], [[log-offset|LogOffset]], [[trace-id|TraceId]], [[causation-id|CausationId]], Type, PayloadJson, OccurredAt. The bus round-trips these. Handlers parse the payload after [[upcast]].",
  ),
  "event-id": t(
    "event-id",
    "EventId",
    "event",
    "Stable identity of one fact. Inbox keys on this.",
    "A duplicate delivery keeps the same EventId. [[inbox]] inserts it; conflict means skip the side effect. The diamond on Alarm’s process is this check.",
  ),
  "partition-key": t(
    "partition-key",
    "PartitionKey",
    "event",
    "Usually the duck id. Shards and the sequencer hash on this, not on EventId.",
    "[[shard-worker-pool|ShardWorkerPool]] assigns a key to a worker. [[per-key-sequencer|PerKeySequencer]] orders [[sequence-number|SequenceNumber]] per key. Cross-key order is not promised — [[hostile-transport|hostile transport]].",
  ),
  "sequence-number": t(
    "sequence-number",
    "SequenceNumber",
    "event",
    "Per-key monotonic sequence from the producer. Not a global clock.",
    "[[per-key-sequencer|PerKeySequencer]] holds a gap until the next number for that [[partition-key|PartitionKey]] arrives. Dashboard does not sequence; hour counts [[commutative|commute]].",
  ),
  "trace-id": t(
    "trace-id",
    "TraceId",
    "event",
    "W3C trace id on every envelope. One squeak is one Aspire trace.",
    "Centers never call each other, so the id must ride the fact. Span names look like alarm: handle.Squeaked. A duplicate adds another span tagged ducknet.duplicate; [[inbox]] still skips.",
  ),
  "causation-id": t(
    "causation-id",
    "CausationId",
    "event",
    "The EventId that caused this fact. AlarmRaised points at the Squeaked that filled the window.",
    "Lets a human follow [[squeaked|Squeaked]] → [[alarm-raised|AlarmRaised]] → [[fee-reserved|FeeReserved]] without Center-to-Center correlation APIs.",
  ),
  version: t(
    "version",
    "Version",
    "event",
    "Payload schema version. Squeaked v1 has no volumeDb; v2 does.",
    "[[upcast]] at the consumer turns leftover v1 into v2. The bus does not rewrite payloads. Handlers parse one version.",
  ),
  "log-offset": t(
    "log-offset",
    "LogOffset",
    "event",
    "Position of this row in Telemetry’s event_log. Consumers checkpoint lastOffset.",
    "Distinct from the metric [[last-offset]]. The envelope field is where this fact sat when appended. Catch-up is log head minus the Center’s checkpoint.",
  ),
  squeaked: t(
    "squeaked",
    "Squeaked",
    "event",
    "A duck squeaked. The fact Telemetry appends and Alarm/Dashboard consume.",
    "v2 payload includes volumeDb. [[loud-duck|LoudDuck]] is duck-1 at 100× weight in Aspire. Alarm runs a [[rate-rule|rate rule]]; Dashboard upserts an hour bucket. Past tense — [[events-are-facts|a fact, not a command]].",
  ),
  "alarm-raised": t(
    "alarm-raised",
    "AlarmRaised",
    "event",
    "AlarmCenter’s rate window tripped. Billing starts a saga.",
    "Emitted via Alarm’s [[outbox]] and [[remote-outbox-dispatcher|RemoteOutboxDispatcher]] POSTing to [[telemetry-http|/bus/events]]. Billing never asked for this; it subscribed. Pair: [[alarm-resolved|AlarmResolved]].",
  ),
  "alarm-resolved": t(
    "alarm-resolved",
    "AlarmResolved",
    "event",
    "The alarm ended. Billing’s fast path releases the fee.",
    "Operator POST /alarms/{duck}/resolve on AlarmCenter, or the rate drops. Billing, if still Reserved, writes [[fee-released|FeeReleased]] with reason AlarmResolved.",
  ),
  "fee-reserved": t(
    "fee-reserved",
    "FeeReserved",
    "event",
    "Billing reserved a fee because an alarm was raised.",
    "Written to Billing’s [[outbox]] when [[billing-sagas]] becomes Reserved. Telemetry’s log gets the fact through [[remote-outbox-dispatcher|RemoteOutboxDispatcher]]. Not a call to Alarm.",
  ),
  "fee-released": t(
    "fee-released",
    "FeeReleased",
    "event",
    "The reserved fee was released — resolve or timeout.",
    "Reason is AlarmResolved (fast) or Timeout (slow [[saga-timeout-worker|compensation]]). The [[saga]] ends Released or Expired. Still a past fact.",
  ),

  "duck-simulator": t(
    "duck-simulator",
    "DuckSimulator",
    "component",
    "Emits Squeaked from simulated ducks. LoudDuck is duck-1 in Aspire.",
    "Lives in Kernel. [[loud-duck|LoudDuck]] squeaks 100× more so [[hot-partition|hot partitions]] are visible. Hands each fact to [[transactional-publisher|TransactionalPublisher]].",
    { code: [{ path: "src/DuckNet.Kernel/Producer/DuckSimulator.cs", why: "LoudDuck emits Squeaked" }] },
  ),
  "transactional-publisher": t(
    "transactional-publisher",
    "TransactionalPublisher",
    "component",
    "duck_state and outbox in one SQLite transaction. Crash-safe produce.",
    "If the process dies after state and before dispatch, [[outbox-dispatcher|OutboxDispatcher]] still appends. The [[event-log|log]] is the source of truth, not the in-memory bus.",
    { code: [{ path: "src/DuckNet.Kernel/Producer/TransactionalPublisher.cs", why: "state + outbox in one tx" }] },
  ),
  "outbox-dispatcher": t(
    "outbox-dispatcher",
    "OutboxDispatcher",
    "component",
    "Drains Telemetry’s outbox into event_log.",
    "Local to the log owner. Consumer Centers use [[remote-outbox-dispatcher|RemoteOutboxDispatcher]] instead, which POST /bus/events. Same idea: do not publish until the write committed.",
  ),
  "event-log": t(
    "event-log",
    "event_log",
    "table",
    "Append-only system of record. TelemetryCenter owns it. Rebuilds start here.",
    "GET /bus/events after an offset is the tail. POST appends. [[http-log-tail-feeder|Feeders]] on Alarm, Dashboard, and Billing catch up from this file, not from each other. [[no-shared-db|Not a shared DB]] — only Telemetry writes it.",
    { live: "log-count" },
  ),
  "http-log-client": t(
    "http-log-client",
    "HttpLogClient",
    "component",
    "HTTP adapter to tail and append Telemetry’s log.",
    "Used by feeders and by [[remote-outbox-dispatcher|RemoteOutboxDispatcher]]. This is infrastructure, not a Center calling another Center’s business rules.",
    { code: [{ path: "src/DuckNet.EventBus/HttpLogClient.cs", why: "tail / append the log" }] },
  ),
  "http-log-tail-feeder": t(
    "http-log-tail-feeder",
    "HttpLogTailFeeder",
    "component",
    "Polls GET /bus/events after lastOffset and PublishAsync onto this Center’s bus.",
    "Each Center has its own feeder and its own topic exchange so three feeders do not triple-publish. Hostile wrappers run after this read. Checkpoint is the Center’s lastOffset.",
  ),
  "duplicator-shuffler": t(
    "duplicator-shuffler",
    "Duplicator + Shuffler",
    "component",
    "Lab hostility: clone some envelopes, shuffle across keys. After the log read.",
    "Never before append — the [[event-log|log]] stays honest. Forces [[inbox]] and [[per-key-sequencer|PerKeySequencer]] to earn their keep. This is [[hostile-transport|hostile transport]] made visible.",
  ),
  "event-bus-factory": t(
    "event-bus-factory",
    "EventBusFactory",
    "component",
    "One-line composition: connection string set → RabbitMQ, else in-memory.",
    "Center *App.cs calls Create(). Handlers do not reference RabbitMQ. Kernel tests keep new InMemoryEventBus().",
    { code: [{ path: "src/DuckNet.EventBus/EventBusFactory.cs", why: "in-memory vs RabbitMQ" }] },
  ),
  "rabbitmq-event-bus": t(
    "rabbitmq-event-bus",
    "RabbitMqEventBus",
    "component",
    "Aspire production IEventBus. Topic per Center, queue per consumer group.",
    "Ack is after DispatchAsync enqueue, not after [[inbox]] commit. Crash mid-handle → redelivery → inbox skip. [[in-memory-event-bus|InMemoryEventBus]] is the test twin.",
    { code: [{ path: "src/DuckNet.EventBus/RabbitMqEventBus.cs", why: "Aspire production path" }] },
  ),
  "in-memory-event-bus": t(
    "in-memory-event-bus",
    "InMemoryEventBus",
    "component",
    "Fan-out in process. Used when ConnectionStrings__rabbitmq is unset.",
    "Center tests and the kernel demo. Same [[bus|IEventBus]] surface as RabbitMQ. Proves handlers do not care which adapter.",
  ),
  upcast: t(
    "upcast",
    "Upcast",
    "component",
    "Consumer rewrites leftover Squeaked v1 to v2 before the handler.",
    "The bus does not know about volumeDb. Mixed logs still project. Handlers parse v2 only. See [[version]].",
  ),
  inbox: t(
    "inbox",
    "Inbox",
    "component",
    "Per-Center table of seen EventIds. Duplicate delivery is a no-op.",
    "Inserted in the same transaction as the side effect ([[alarm-store|AlarmStore]], hour bucket, or saga). The [[bus|IEventBus]] may deliver twice — [[at-least-once]]. Not shared across Centers.",
    { code: [{ path: "src/DuckNet.Kernel/Consumer/Inbox.cs", why: "dedupe EventId" }] },
  ),
  "per-key-sequencer": t(
    "per-key-sequencer",
    "PerKeySequencer",
    "component",
    "Buffers until SequenceNumber is next for that PartitionKey.",
    "Alarm uses it so the rate window sees per-duck order. Dashboard does not — [[commutative|commutative]] upserts. Cross-key shuffle is allowed.",
  ),
  "retry-pipeline": t(
    "retry-pipeline",
    "RetryPipeline",
    "component",
    "A few attempts, then DLQ, then advance lastOffset. The partition continues.",
    "Poison [[squeaked|Squeaked]] must not stall a shard. [[dlq|DLQ]] is per Center. Replay can fix the payload or skip.",
  ),
  "shard-worker-pool": t(
    "shard-worker-pool",
    "ShardWorkerPool",
    "component",
    "Hash PartitionKey onto N workers so a hot duck does not starve quiet keys.",
    "Aspire uses 3 shards and a handle delay so lag is visible. SHARD_COUNT=1 re-starves. [[loud-duck|LoudDuck]] is the demo. [[hot-partition|Hot partition]] is the failure mode.",
    { live: "shard-lag", code: [{ path: "src/DuckNet.Kernel/Consumer/ShardWorkerPool.cs", why: "hot key isolation" }] },
  ),
  "remote-outbox-dispatcher": t(
    "remote-outbox-dispatcher",
    "RemoteOutboxDispatcher",
    "component",
    "Drains a Center’s outbox by POST /bus/events on Telemetry.",
    "Alarm and Billing publish [[alarm-raised|AlarmRaised]] / [[fee-reserved|Fee*]] this way. HTTP to the log owner is append, not a business call into Telemetry’s rules.",
  ),
  dlq: t(
    "dlq",
    "DLQ",
    "table",
    "dead_letter_queue. Retry exhausted; offset still advances.",
    "GET /dlq on that Center. Replay with fix=true or skip. One poison must not block the partition. Each Center owns its rows — [[no-shared-db]].",
    { live: "dlq-count" },
  ),
  rebuild: t(
    "rebuild",
    "Rebuild",
    "component",
    "Truncate Dashboard’s read model, reset offset to 0, replay the log.",
    "Proves the projector is disposable [[cqrs|CQRS]]. The [[event-log|log]] is the source of truth. Inbox rows go with the truncate.",
    { live: "rebuild" },
  ),
  "alarm-store": t(
    "alarm-store",
    "AlarmStore",
    "component",
    "Rate window + alarm rows + outbox in Alarm’s SQLite, one transaction with inbox.",
    "[[rate-rule|Rate rule]] counts unique squeaks in [[window]]. Crosses [[threshold]] → [[alarm-raised|AlarmRaised]]. Own file, not Telemetry’s.",
    { code: [{ path: "src/DuckNet.AlarmCenter/AlarmStore.cs", why: "rate rule + outbox" }] },
  ),
  "dashboard-read-model": t(
    "dashboard-read-model",
    "DashboardReadModel",
    "component",
    "Hour buckets plus volume_db. Throw it away; replay rebuilds it.",
    "Upsert on (duck, hour). [[commutative]] under shuffle. No outbox — Dashboard does not emit facts.",
  ),
  "billing-store": t(
    "billing-store",
    "BillingStore",
    "component",
    "Saga persistence. Primary key is alarm_id. States: Reserved, Released, Expired.",
    "handle(AlarmRaised) reserves. handle(AlarmResolved) releases. Timeout worker compensates if still Reserved. Own SQLite.",
    { code: [{ path: "src/DuckNet.BillingCenter/BillingStore.cs", why: "Reserved | Released | Expired" }] },
  ),
  "saga-timeout-worker": t(
    "saga-timeout-worker",
    "SagaTimeoutWorker",
    "component",
    "Compensation if the alarm is not resolved in time. Aspire uses 15s.",
    "SAGA_TIMEOUT_SECONDS defaults to 300; AppHost sets 15 so the slow path is demoable. Writes [[fee-released|FeeReleased]] reason=Timeout and marks [[billing-sagas]] Expired.",
    { live: "saga-timeout", code: [{ path: "src/DuckNet.BillingCenter/SagaTimeoutWorker.cs", why: "timeout compensation" }] },
  ),
  "rate-rule": t(
    "rate-rule",
    "Rate rule",
    "component",
    "Raise when unique squeaks in the event-time window exceed ALARM_RATE_THRESHOLD.",
    "ALARM_WINDOW_SECONDS is the sliding window. Defaults 10 in 60s. Live knobs: [[threshold]], [[window]]. Event-time, not wall clock of the handler.",
  ),
  "telemetry-http": t(
    "telemetry-http",
    "GET/POST /bus/events",
    "component",
    "Telemetry’s HTTP for tail and append. The log’s public seam.",
    "Feeders GET after offset. Producers and [[remote-outbox-dispatcher|RemoteOutboxDispatcher]] POST. POST /bus/poison is the mis-demo. Not a business API for Alarm or Billing.",
  ),
  "alarm-consumer": t(
    "alarm-consumer",
    "AlarmConsumer",
    "component",
    "handle.Squeaked for AlarmCenter. DispatchAsync onto shards.",
    "Subscribe(alarm-center) — a [[consumer-group]]. After [[upcast]], the rate rule runs inside the inbox transaction.",
    { code: [{ path: "src/DuckNet.AlarmCenter/AlarmConsumer.cs", why: "handle.Squeaked" }] },
  ),
  "dashboard-consumer": t(
    "dashboard-consumer",
    "DashboardConsumer",
    "component",
    "Projects Squeaked into hour buckets. No sequencer, no outbox.",
    "Subscribe(dashboard-projector). [[inbox]] + upsert in one tx. [[rebuild]] is the other writer.",
  ),
  "billing-consumer": t(
    "billing-consumer",
    "BillingConsumer",
    "component",
    "handle AlarmRaised and AlarmResolved. Starts and completes sagas.",
    "Subscribe(billing-center). Never opens Alarm’s SQLite. The [[saga]] is Billing’s private state machine.",
    { code: [{ path: "src/DuckNet.BillingCenter/BillingConsumer.cs", why: "AlarmRaised / AlarmResolved" }] },
  ),
  drop: t(
    "drop",
    "Drop",
    "concept",
    "Duplicate EventId: skip the side effect, do not retry, do not DLQ.",
    "The diamond’s yes branch. [[inbox]] already has the id. Advancing is correct; counting twice is not. Contrast [[dlq|DLQ]], which is handler failure, not a known duplicate.",
  ),

  "squeaks-by-duck-hour": t(
    "squeaks-by-duck-hour",
    "squeaks_by_duck_hour",
    "table",
    "Dashboard’s read model. One row per duck per UTC hour, plus volume_db.",
    "Disposable. [[rebuild]] truncates it. Counts [[commutative|commute]], so shuffle is fine. This UI’s Read model tab is a query over this table.",
  ),
  alarms: t(
    "alarms",
    "alarms",
    "table",
    "AlarmCenter’s current alarm rows. Raised until resolved.",
    "GET /alarms. Operator resolve emits [[alarm-resolved|AlarmResolved]]. Not visible in Billing’s DB — Billing has [[billing-sagas]].",
    { live: "alarms" },
  ),
  "squeak-window": t(
    "squeak-window",
    "squeak_window",
    "table",
    "Event-time sliding window of squeaks per duck. Feeds the rate rule.",
    "Owned by Alarm. Distinct from Dashboard hour buckets. Deleting Alarm’s DB loses the window; catch-up from [[event-log|event_log]] rebuilds what the log still has.",
  ),
  "billing-sagas": t(
    "billing-sagas",
    "billing_sagas",
    "table",
    "Billing’s saga rows. PK = alarm_id. Reserved, Released, or Expired.",
    "GET /sagas. Fast resolve → Released. Miss the [[saga-timeout|timeout]] → Expired. [[no-shared-db|Alarm cannot see this table]].",
    { live: "saga-state" },
  ),
  "dead-letter-queue": t(
    "dead-letter-queue",
    "dead_letter_queue",
    "table",
    "Schema name for each Center’s DLQ. Same idea, separate files.",
    "See [[dlq|DLQ]]. Replay and skip are per Center. Offset still moved so the shard does not stall.",
  ),
  outbox: t(
    "outbox",
    "outbox",
    "table",
    "Transactional outbox. Side effect and ‘I will publish’ in one commit.",
    "Telemetry: state + outbox → [[outbox-dispatcher|OutboxDispatcher]] → [[event-log]]. Alarm/Billing: store + outbox → [[remote-outbox-dispatcher|RemoteOutboxDispatcher]] → POST /bus/events. Do not PublishAsync from the handler without this.",
  ),

  "last-offset": t(
    "last-offset",
    "lastOffset",
    "metric",
    "This Center’s checkpoint in event_log. The consumer’s cursor.",
    "Advanced after a successful handle, a known duplicate [[drop]], or a [[dlq|DLQ]] write. Gap to Telemetry’s log head is [[catch-up]]. Distinct from envelope [[log-offset|LogOffset]].",
    { live: "last-offset" },
  ),
  "catch-up": t(
    "catch-up",
    "behind log",
    "metric",
    "log head minus this Center’s lastOffset. How far the feeder still has to go.",
    "Stop Alarm, let Telemetry append, start Alarm — this number climbs then falls. Catch-up is from the [[event-log|log]], not from another Center.",
    { live: "catch-up" },
  ),
  "log-count": t(
    "log-count",
    "log count",
    "metric",
    "Rows in Telemetry’s event_log. The system-of-record length.",
    "Grows with [[squeaked|Squeaked]] and with Center-emitted facts that were POSTed back. Not the same as Dashboard’s [[total-squeaks|squeak total]] (a projection).",
    { live: "log-count" },
  ),
  "alarm-count": t(
    "alarm-count",
    "alarm count",
    "metric",
    "Active alarms in AlarmCenter’s store.",
    "LoudDuck plus a low [[threshold]] fills this. Resolve from the live panel emits [[alarm-resolved|AlarmResolved]].",
    { live: "alarm-count" },
  ),
  "dlq-count": t(
    "dlq-count",
    "dlqCount",
    "metric",
    "Rows in this Center’s dead_letter_queue.",
    "POST /bus/poison on Telemetry injects one malformed [[squeaked|Squeaked]]. Each consumer retries, writes [[dlq|DLQ]], continues. See GET /dlq.",
    { live: "dlq-count" },
  ),
  threshold: t(
    "threshold",
    "ALARM_RATE_THRESHOLD",
    "metric",
    "Raise when unique squeaks in the window are greater than this.",
    "Default 10. Pairs with [[window|ALARM_WINDOW_SECONDS]]. The [[rate-rule|rate rule]] reads these env knobs. Live value is on Alarm /stats.",
    { live: "threshold" },
  ),
  window: t(
    "window",
    "ALARM_WINDOW_SECONDS",
    "metric",
    "Event-time sliding window for the rate rule, in seconds.",
    "Default 60. Event-time uses OccurredAt on the envelope, not handler wall clock. See [[squeak-window]] and [[rate-rule]].",
    { live: "window" },
  ),
  "shard-lag": t(
    "shard-lag",
    "shard queue / lag",
    "metric",
    "Per-worker queue depth and lag. Hot key isolation is working if only one shard is hot.",
    "[[loud-duck|LoudDuck]] hashed onto one worker. Quiet ducks on other shards stay near the handle delay. SHARD_COUNT=1 makes every duck wait. [[hot-partition]].",
    { live: "shard-lag" },
  ),
  "saga-state": t(
    "saga-state",
    "saga state",
    "metric",
    "Reserved, Released, or Expired — Billing’s view of one alarm.",
    "Reserved after [[alarm-raised|AlarmRaised]]. Released after [[alarm-resolved|AlarmResolved]]. Expired after [[saga-timeout-worker|timeout]]. Counts on /stats: reserved / released / expired.",
    { live: "saga-state" },
  ),
  "saga-timeout": t(
    "saga-timeout",
    "SAGA_TIMEOUT_SECONDS",
    "metric",
    "How long Billing waits in Reserved before compensating. Aspire: 15s.",
    "Default 300. AppHost shortens it so the slow path is demoable. The worker is [[saga-timeout-worker]].",
    { live: "saga-timeout" },
  ),
  reserved: t(
    "reserved",
    "Reserved",
    "metric",
    "Saga opened, fee held, waiting for resolve or timeout.",
    "See [[saga-state]] and [[fee-reserved|FeeReserved]]. GET /sagas lists rows still in this state with expiresAt.",
    { live: "reserved" },
  ),
  released: t(
    "released",
    "Released",
    "metric",
    "Saga completed because the alarm resolved in time.",
    "[[fee-released|FeeReleased]] reason=AlarmResolved. Contrast [[expired|Expired]], which is compensation.",
    { live: "released" },
  ),
  expired: t(
    "expired",
    "Expired",
    "metric",
    "Saga compensated: still Reserved when the timeout fired.",
    "[[fee-released|FeeReleased]] reason=Timeout. The alarm may still be up on AlarmCenter — Centers do not share that row.",
    { live: "expired" },
  ),
  "total-squeaks": t(
    "total-squeaks",
    "totalSqueaks",
    "metric",
    "Sum of hour-bucket counts in Dashboard’s read model.",
    "A projection, not the log length. After [[rebuild]] it should match counted [[squeaked|Squeaked]] (minus duplicates dropped by [[inbox]]).",
    { live: "total-squeaks" },
  ),

  "consumer-group": t(
    "consumer-group",
    "Consumer group",
    "concept",
    "Logical subscriber identity. alarm-center, dashboard-projector, billing-center.",
    "[[bus|IEventBus]].SubscribeAsync(group) fans out: one copy per group. RabbitMQ queue name includes the group. Inbox is per Center, hence per group.",
  ),
  cqrs: t(
    "cqrs",
    "CQRS",
    "concept",
    "Write the log; read a private projection. Dashboard can be deleted.",
    "Telemetry’s [[event-log|event_log]] is the write model for the system of record. [[squeaks-by-duck-hour]] is a read model. [[rebuild]] is the punchline.",
  ),
  saga: t(
    "saga",
    "Saga",
    "concept",
    "Long-lived state machine in one Center, driven by facts from others, compensated on timeout.",
    "Billing’s saga is not a distributed transaction. No 2PC. [[alarm-raised|AlarmRaised]] / [[alarm-resolved|AlarmResolved]] / timer. Private table [[billing-sagas]].",
  ),
  poison: t(
    "poison",
    "Poison message",
    "concept",
    "A payload the handler cannot parse. Retry, then DLQ, stream continues.",
    "POST /bus/poison or INJECT_POISON_EVENT. [[retry-pipeline|RetryPipeline]] must not block the [[partition-key|partition]]. Inspect GET /dlq; replay with a fixed payload.",
  ),
  "loud-duck": t(
    "loud-duck",
    "LoudDuck",
    "concept",
    "duck-1 squeaks ~100× more than the others. Makes hot partitions obvious.",
    "LOUD_DUCK_ID=duck-1 in Aspire. Pair with [[shard-worker-pool|ShardWorkerPool]] and HANDLE_DELAY_MS. One shard’s [[shard-lag|lag]] climbs; others stay near real time — unless SHARD_COUNT=1.",
  ),
  "hot-partition": t(
    "hot-partition",
    "Hot partition",
    "concept",
    "One key hashes onto one worker; that queue grows; quiet keys on the same worker wait.",
    "Fix in this lab: more shards, not a faster handler. [[loud-duck|LoudDuck]] is the load. [[shard-lag]] is the evidence.",
  ),
  commutative: t(
    "commutative",
    "Commutative projection",
    "concept",
    "Applying facts in any order yields the same read model. Dashboard hour counts are this.",
    "That is why Dashboard skips [[per-key-sequencer|PerKeySequencer]]. Alarm’s rate window does not commute — order per duck matters — so Alarm sequences.",
  ),
};

export function getTerm(id: string): Term | undefined {
  return terms[id];
}

export function allTermIds(): string[] {
  return Object.keys(terms);
}
